version: '3'

services:
  web:
    build:
      context: ./channel_service
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python3 manage.py migrate &&
              python3 manage.py wait_for_db &&
              python3 manage.py load_fixtures &&
              python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  redis:
    image: redis:alpine
    restart: always
    expose:
        - 6379
  celery:
    restart: always
    build:
      context: ./channel_service
    command: celery -A config worker -B
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
  vue:
    build:
      context: ./vue_app
      dockerfile: Dockerfile
    restart: always
    command: npm run dev -- --host 0.0.0.0
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - web
volumes:
  postgres_data:
