# Generated by Django 4.0.4 on 2022-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер по порядку')),
                ('bid_id', models.IntegerField(verbose_name='Номер заказа')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Стоимость USD')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Стоимость RUB')),
                ('delivery_time', models.DateField(verbose_name='Срок поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='DefaultRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Доллар США', max_length=255, verbose_name='Наименование валюты')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Курс')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Дефолтный курс',
                'verbose_name_plural': 'Дефолтные курсы',
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bid_id'], name='main_bid_bid_id_9e5718_idx'),
        ),
    ]
