"""
Django settings for channel_service project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG', default=1)))

ALLOWED_HOSTS = ['*']

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
# ]
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ORIGIN_ALLOW_ALL = True

# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:3000',
# ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'django_celery_results',

    'main',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('SQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('SQL_DATABASE', os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': os.environ.get('SQL_USER', 'user'),
        'PASSWORD': os.environ.get('SQL_PASSWORD', 'password'),
        'HOST': os.environ.get('SQL_HOST', 'localhost'),
        'PORT': os.environ.get('SQL_PORT', '5432'),
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'task': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/task.log',
            'formatter': 'verbose'
        },

    },
    'loggers': {
        'task': {
            'handlers': ['task', 'console'],
            'level': 'INFO',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = '6379'
CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_RESULT_EXPIRES = 7*86400
CELERY_CACHE_BACKEND = 'django-cache'


GOOGLE_SHEETS_CREDENTIALS = {
    "type": "service_account",
    "project_id": "channel-service-350903",
    "private_key_id": "11a89af9af290bf4875e909f193a80ee03fadade",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCym4RrjjGtmXfp\n05fJf6/6zzZP/3FzXPJLHdFxFBvR7+T4p7TOZHcbsGey/Hw8oW7tocvL68PGWz5F\niNVOvIznNIHW6Ovq5bLzRdrUx8tw8Xx6ar9v2WiJYMHrYvL2Mxe+0rj+b/MibBOz\nQaG69YB3MunR56xuJnNqgYZYqQHCzmp9xsRI4be86FiJ6sjh4WUZXrkuiP08kaU2\nuceUIdOmWK8+BUcE1SwCgBX/rj163HouOvmsPAH2sFvG6KBHxU13y0CT2IVwjR5E\nDQbwoV4ipUKPrkccp7HrE9k/pSCMd2L7NrRoOd4VMZ1PsB4recYYXkrM54UlccQa\n0ANGoYlpAgMBAAECgf9QDuWMUHB0IBZf+ThQWavIAJmXwihYTZFNmlAHH7xYne9E\nhefFm8LH5oqU8BfAFZxjZ+KxxTw77So8gNkcMef2utJ4Qm99GvjbkrRELEpElfn1\n5WNp/0mcSoKhv/in4r8CCfJiGkwhYdByyTh1VRYAWBH2xKHFvfZ+BxDxLNBdQOcG\npTGpymj+ULWG9dDRwj0tCLClGP07LjSrkv8Uk8l8iEH+6wf2SwjS4xudbSvfEDaz\nhZvSEjPQwxl6coXFERTQQLfB7K2cQyz0dFf7Geyv30x1P5CggDIvgb7WtlwQLZdN\nlsCnWfY8Ic8wbRSKjOzemtB5UxpYS8UfLJr8yyECgYEA+UV5OtIsNN7UHr7TwnLG\n3H9RCKImKqCCvUKtrdR3JbbswwRBpoSaFwAzuwgoaWAduXeSgRZKksbIEJ8xMsTU\n+nH86erPXRu3R4UWND/B6rrW1MaXXRxSpXO4FpPbm+ocnd6Cnrsc13nM2BBL+IqC\nB4kCVP9qHekScqRYyKpK5NkCgYEAt229Jp06FpdNOHi5rSFpmgmMmCqy1laFSVUG\ntZHEoYXa7LiJAUGZWMqzIYP+xpy7N3p0d9JVxnJbYF7T3s4Io5qIjUuTnn49f0Ev\nC7lcmCFtakKSH0Or5HOPOdAiUCZ0FOj9lNssYnDL2khY8vKpvIHoGVJ6cXRfD9Vn\nqcv4rxECgYBgg6zHwJ7LLcfVy680J7qln0oh3J6IfLOCUjHrD0u+t4/+hkRhFBCR\nfUuKTENRYZzAtfJsttPS9tJ51Rl4fcu02LPDYl49v8B8GaSaQGF14DfUFLyAmbnK\nQ/7wBvnN6ZyA56mNigdFyuwscErqBb8I6dyUSnys7hRtfQK/V2g+KQKBgEsw9/XJ\nQ9OY6DW6/1oiNTjIq1KBRlgolXCvIxXxECqqRUj+iGL0chj81ptpkVn3S6N9Vhr8\nJN85Z43EsZNG4DG4mjtZfMTeuPTeUpu6u2M9aK3DZkTcp6z5Vf/7+uTiLnmX3MNV\naQddd6MePyAwKzY0BmHC9qBldMZ304u+Kk4RAoGBANUYuLaWy11jdUoN4vZUcWHP\nscUmKOD1TIAq0ppc/dtoUQ1NvIvMBYysCXwM/HOLyzj6ozk7YW4LBWugVEYcyFYK\nkbtTWGvZLXiYoEjNeh51imZXYxJPX21PboI2n5Je6rJuD6ySudNDu/WiN1RlYC4K\nWIZmb4n/2eO8hVWd6kgL\n-----END PRIVATE KEY-----\n",
    "client_email": "channel-service@channel-service-350903.iam.gserviceaccount.com",
    "client_id": "100713502371838679897",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/channel-service%40channel-service-350903.iam.gserviceaccount.com"
}
SPREAD_SHEET_NAME = 'Заявки Канал Сервис'
SHEET_NAME = 'Заявки'
